### ISSUE TITLE
Classmarker-Test

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/form-validation-quiz-4ahif-SimonPrimetzhofer#1]
Dear Mr. Stropek!

I opened the classmarker.com page and registered myself as intentioned.
There is a test visible for me, but the name contains 4BHIF.

Should we do this test or will there be an extra one for us too?

Greetings,

Simon Primetzhofer

**Comment by rstropek** [comment]
@SimonPrimetzhofer sorry for my mistake. Yes, it is the right test. It was a bug in the test's name. I fixed it.

Sorry for my mistake, greetings,
Rainer Stropek.
