### ISSUE TITLE
Link to the public internet

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/form-validation-quiz-4ahif-SimonPrimetzhofer#2]
Dear Mr. Stropek!

Here is the link to my solution:
https://rawgit.com/SimonPrimetzhofer/FormValidation/master/index.html

Greetings,

Simon Primetzhofer

UPDATE: I just found a little mistake... Updated version comming soon.

**Comment by rstropek** [comment]
@SimonPrimetzhofer I also found one ;-) Try changing the channel using keyboard (e.g. press *o* for *Other*). Your validation code will not be triggered.

Greetings,
Rainer Stropek.

**Comment by SimonPrimetzhofer** [comment]
I just corrected the mistake I have found.

What exactly do you mean with that?
If I open the Drop-Down and press 'o', "Other" is marked blue and when I click Enter after that, it works...

Greetings,

Simon Primetzhofer

**Comment by SimonPrimetzhofer** [comment]
This is the new link: 
https://rawgit.com/rstropek-teaching/form-validation-quiz-4ahif-SimonPrimetzhofer/master/index.html

**Comment by rstropek** [comment]
Formatting doesn't work. I get these errors in the console:

```
Failed to load resource: the server responded with a status of 404 () bootstrap.js
Failed to load resource: the server responded with a status of 404 () jquery.js
...
```

Greetings,
Rainer Stropek

**Comment by rstropek** [comment]
If you click on channel *Other* with the mouse, everything is fine. If you move the focus to the field using the *Tab* key and press *o*, *Other* is selected **but** the text area does not appear.

Does that help?

Regards,
Rainer Stropek.

**Comment by SimonPrimetzhofer** [comment]
Yeah, I forgot to update my other repository. xD

Oh thanks, I'll take a closer look on that.

Greetings,
Simon Primetzhofer
