### ISSUE TITLE
Link to the public internet - second try

### ISSUE THREAD

**Issue by SimonPrimetzhofer** [rstropek-teaching/form-validation-quiz-4ahif-SimonPrimetzhofer#3]
Dear Mr. Stropek!

This is the new link to my solution:
https://rawgit.com/SimonPrimetzhofer/FormValidation/master/index.html

But there is one problem: 
The thing which you mentioned with navigating to "Other" with the keyboard works on my local browser session with browser-sync as intentioned but not on the internet using rawgit.com... Strange.

I can show it to you in the next lesson if you want to. 

Greetings,

Simon Primetzhofer

**Comment by rstropek** [comment]
Hi @SimonPrimetzhofer, everything works fine now. Congrats, well done 👍 Your extra point is secured.

I added some tips as comments to your code.

Greetings,
Rainer Stropek.
